name: game_repository
description: Contacts node backend
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.13.1

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  http: ^1.1.0
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0
